### ISSUE TITLE
The ciphertool is not working on SI 4.2.0

### ISSUE THREAD

**Issue by GihanAyesh** [wso2/api-manager#2306]
### Description

The ciphertool is not working on SI 4.2.0

### Steps to Reproduce

go to bin and run the ciphertool.sh script

### Affected Component

SI

### Version

4.2.0

### Relevant Log Output

```shell
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.wso2.carbon.secvault.ciphertool.CipherToolInitializer.<clinit>(CipherToolInitializer.java:41)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 1 more
```
